FROM node:18 as build

WORKDIR /app
COPY frontend/package*.json /app/

RUN npm install

COPY frontend /app

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]