version: '3.12'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-service
    container_name: ner_backend
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    networks:
      - ner_net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-site
    container_name: ner_frontend
    ports:
      - "3000:80"
    networks:
      - ner_net

networks:
  ner_net:
    driver: bridge